core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
    path('accounts/profile/', include('users.urls', namespace='accounts_profile')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('tasks/', views.task_list, name= 'task_list'),
    path('tasks/add', views.task_add, name= 'task_add'),
    path('tasks/<str:task_id>/', views.task_detail, name= 'task_detail'),
    path('tasks/<str:task_id>/delete/', views.task_delete, name= 'task_delete'),
    path('tasks/<str:task_id>/edit/', views.task_edit, name= 'task_edit'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'accounts_profile'

urlpatterns = [
    path('', views.profile_view, name='profile'),
    path('edit/', views.profile_edit_view, name='profile_edit')
]

tasks/models.py
import shortuuid
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.CharField(
        primary_key=True,
        default=shortuuid.uuid,
        max_length=22,
        editable=False
    )
    name = models.CharField(max_length=100)
    task_type = models.CharField(max_length=50, choices=[
        ('work', 'Work'),
        ('exercise', 'Exercise'),
        ('household', 'Household'),
        ('leisure', 'Leisure'),
    ])
    frequency = models.CharField(max_length=50, choices=[  
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    ])
    duration = models.SmallIntegerField(validators=[MinValueValidator(1)]) 
    priority = models.CharField(max_length=50, choices=[ 
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    ])
    physical_effort = models.CharField(max_length=50, choices=[  
        ('light', 'Light'),
        ('moderate', 'Moderate'),
        ('intense', 'Intense'),
    ])
    tiredness_factor = models.CharField(max_length=50, choices=[
        ('relaxing', 'Relaxing'),
        ('neutral', 'Neutral'),
        ('draining', 'Draining')
    ]) 
    
    def save(self, *args, **kwargs):
        if self.name:
            self.name = self.name.capitalize()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=50, choices=[('admin', 'Admin'), ('regular', 'Regular')], default='regular')
    consent_given = models.BooleanField(default=False)
    consent_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'task_type', 'frequency', 
                  'duration', 'priority', 'physical_effort', 
                  'tiredness_factor']
        labels = {
            'duration': 'Duration(in minutes)',
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from allauth.account.forms import SignupForm

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.utils.safestring import mark_safe
from .models import Task
from .forms import TaskForm

@login_required(login_url="/users/login/")
def task_list(request):
    task_type = request.GET.get('task_type', '')
    priority = request.GET.get('priority', '')


    tasks = Task.objects.filter(user=request.user).order_by('name')

    if task_type:
        tasks = tasks.filter(task_type=task_type)
    if priority:
        tasks = tasks.filter(priority=priority)
    
    return render(request, 'tasks/task_list.html', {'tasks': tasks,})


@login_required(login_url="/users/login/")
def task_detail(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    return render(request, 'tasks/task_detail.html', {'task' : task})


@login_required(login_url="/users/login/")
def task_add(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user  # Assign the logged-in user
            task.save()
            messages.success(request, "Task added successfully!")
            return redirect('tasks:task_list')
    else:
        form = TaskForm()
    return render(request, 'tasks/task_add.html', {'form': form})

@login_required(login_url="/users/login/")
def task_delete(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    messages.success(request, mark_safe(f'Task "<strong>{task.name}</strong>" has been successfully deleted.'))
    print(f'Task "{task.name}" has been successfully deleted.')

    return redirect('tasks:task_list')


@login_required(login_url="/users/login/")
def task_edit(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task_list')
    
    else:
        form = TaskForm(instance=task)

    return render(request, 'tasks/task_edit.html', {'form' : form, 'task': task})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import  ProfileUpdateForm, CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

@login_required
def profile_view(request):
    return render(request, 'users/profile.html', {'user': request.user})

@login_required
def profile_edit_view(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('accounts_profile:profile')  # Redirect to the profile page
    else:
        form = ProfileUpdateForm(instance=request.user)

    return render(request, 'users/profile_edit.html', {'form': form})  

# def register_view(request):

#     if request.method == "POST":
#         form = CustomUserCreationForm(request.POST)
#         if form.is_valid():
#             login(request, form.save())
#             return redirect('tasks:task_list')
#     else:
#         form = CustomUserCreationForm()


#     return render(request, 'users/register.html', {'form' : form})

# def login_view(request):
#     if request.method == "POST":
#         form = AuthenticationForm(data=request.POST)
#         if form.is_valid():
#             login(request, form.get_user())
#             if 'next' in request.POST:
#                 return redirect(request.POST.get('next'))
#             else:
#                 return redirect('tasks:task_list')
#     else:
#         form = AuthenticationForm()

#     return render(request, 'users/login.html', {'form' : form})

# @require_http_methods(["POST"])
# def logout_view(request):
#     logout(request)
#     return render(request, 'users/logged_out.html')

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Task Manager{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        {% block header %}
        <h1>Task Manager</h1>
        {% endblock %}
        {% block profile_section %}
        <div class="user-profile">
            <a href="{% url 'accounts_profile:profile' %}" class="profile-link">👤 Profile</a>
        </div>
        {% endblock %}
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>&copy; 2025 Task Manager</p>
    </footer>
</body>
</html>

tasks/templates/tasks/task_add.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block header %}
<a href="{% url 'tasks:task_list' %}" class="back-to-list">
     Back to Task List
</a>
<h1>Add Task</h1>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Task</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block title %}Task Details{% endblock %}

{% block header %}
<a href="{% url 'tasks:task_list' %}" class="back-to-list">
    Back to Task List
</a>
<h1>Task Details</h1>
{% endblock %}

{% block content %}
<div class="container">
    <h2 class="task-title">{{ task.name }}</h2>
    <div class="task-info"><strong>Type:</strong> {{ task.task_type }}</div>
    <div class="task-info"><strong>Priority:</strong> {{ task.priority }}</div>
    <div class="task-info"><strong>Frequency:</strong> {{ task.frequency }}</div>
    <div class="task-info"><strong>Duration:</strong> {{ task.duration }} minutes</div>
    <div class="task-info"><strong>Physical Effort:</strong> {{ task.physical_effort }}</div>
    <div class="task-info"><strong>Tiredness Factor:</strong> {{ task.tiredness_factor }}</div>

    <!-- Buttons -->
    <div class="button-container">
        <a href="{% url 'tasks:task_edit' task.id %}" class="button edit-btn">Edit Task</a>
        <a href="{% url 'tasks:task_delete' task.id %}" 
        class="button delete-btn" 
        onclick="return confirmDeleteWithEvent(event, '{{ task.name }}');">
        Delete Task
     </a>

    </div>
</div>
{% endblock %}


<script>
    function confirmDeleteWithEvent(event, taskName) {
        console.log(`Trying to delete task: ${taskName}`);
        const confirmed = confirm(`Are you sure you want to delete "${taskName}"?`);
        if (!confirmed) {
            event.preventDefault(); // Stop the link action if not confirmed
        }
        return confirmed;
    }
</script>

tasks/templates/tasks/task_edit.html
{% extends 'base.html' %}

{% block title %}Edit Task{% endblock %}

{% block header %}
<a href="{% url 'tasks:task_detail' task.id %}" class="back-to-details">
    &#8592; Back to Task Details
</a>
<h1>Edit Task</h1>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block title %}Your Tasks{% endblock %}


{% block content %}
{% load query_params %}

<div id="notification-container"></div> <!-- Notification container -->

<div class="container">
    <h2>Your Tasks</h2>
    <ul class="task-list">
        {% for task in tasks %}
        <li onclick="window.location.href='{% url 'tasks:task_detail' task.id %}'">
            <div class="task-details">
                <span class="task-name">{{ task.name }}</span>
                <span class="task-meta">{{ task.task_type }} | {{ task.priority }}</span>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="button-container">
      <a href="{% url 'tasks:task_add' %}" class="add-task-btn">+ Add Task</a>
      <div class="dropdown">
          <button class="filter-button">Filters</button>
          <div class="dropdown-content">
              <div class="sub-dropdown">
                  <div class="dropdown-item">Priority</div>
                  <div class="sub-dropdown-content">
                      <a href="{% toggle_query_param 'priority' 'high' %}" class="dropdown-item">High</a>
                      <a href="{% toggle_query_param 'priority' 'medium' %}" class="dropdown-item">Medium</a>
                      <a href="{% toggle_query_param 'priority' 'low' %}" class="dropdown-item">Low</a>
                  </div>
              </div>
              <div class="sub-dropdown">
                  <div class="dropdown-item">Task Type</div>
                  <div class="sub-dropdown-content">
                      <a href="{% toggle_query_param 'task_type' 'work' %}" class="dropdown-item">Work</a>
                      <a href="{% toggle_query_param 'task_type' 'exercise' %}" class="dropdown-item">Exercise</a>
                      <a href="{% toggle_query_param 'task_type' 'household' %}" class="dropdown-item">Household</a>
                      <a href="{% toggle_query_param 'task_type' 'leisure' %}" class="dropdown-item">Leisure</a>
                  </div>
              </div>
              <a href="{% url 'tasks:task_list' %}" class="dropdown-item reset-filters">Reset Filters</a>
          </div>
      </div>
  </div>
{% endblock %}

users/templates/users/logged_out.html
{% extends "base.html" %}
{% block profile_section %}{% endblock %}

{% block content %}
<head>
    <title>Logged Out</title>
</head>
<body>
    <h1>You have been logged out</h1>
    <a href="{% url 'users:login' %}">Log in again</a>
</body>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block profile_section %}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="form-title">Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if request.GET.next %}
        <input type="hidden" name"next" value="{{ request.GET.next}}"/>
        {% endif %}
        <button type="submit" class="submit-btn">Login</button>
    </form>
    <div class="form-footer">
        <p>Don't have an account? <a href="{% url 'users:register' %}" class="register-link">Register here</a></p>
        <a href="{% url 'account_login' %}">Login via google</a>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}
<div class="container">
    <h2>User Profile</h2>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>First Name:</strong> {{ user.first_name }}</p>
    <p><strong>Last Name:</strong> {{ user.last_name }}</p>
    <p><strong>Date Joined:</strong> {{ user.date_joined|date:"M d, Y H:i" }}</p>

    <div class='button-container'>
        <a href="{% url 'accounts_profile:profile_edit' %}" class="button edit-btn">Edit Profile</a>
        <a href="{% url 'tasks:task_list' %}" class="back-to-list">Back to Task List</a>
        <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            <button class="logout-btn">Logout</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}

{% block content %}
<div class="container">
    <h2>Update Profile</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <a href="{% url 'accounts_profile:profile' %}" class="back-to-list">Cancel</a>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}
{% block profile_section %}{% endblock %}

{% block content %}
<div class="container">
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}